"""add instruments_owned to users

Revision ID: 5410aa78a8a0
Revises: ce498fd056b5
Create Date: 2026-01-05 15:40:28.968826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5410aa78a8a0'
down_revision = 'ce498fd056b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instruments_owned', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('instruments_owned')

    # ### end Alembic commands ###
