"""add brand and location_name columns to instruments

Revision ID: 5b2e118eb330
Revises: 5410aa78a8a0
Create Date: 2026-01-05 16:32:46.949330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2e118eb330'
down_revision = '5410aa78a8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jam_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'skipped', name='jam_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jam_requests', schema=None) as batch_op:
        batch_op.create_index('idx_sender_receiver', ['sender_id', 'receiver_id'], unique=False)

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_column('brand')

    with op.batch_alter_table('jam_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_sender_receiver')

    op.drop_table('jam_requests')
    # ### end Alembic commands ###
