"""add jam fields to user and jam_requests table

Revision ID: ce498fd056b5
Revises: d3e7ffd5dbeb
Create Date: 2026-01-05 14:47:03.014065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce498fd056b5'
down_revision = 'd3e7ffd5dbeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Table jam_requests already exists
    user_role = sa.Enum('owner', 'renter', 'jammer', name='user_role')
    user_role.create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', user_role, nullable=True, default='jammer'))
        batch_op.add_column(sa.Column('genres_enjoyed', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('instruments_played', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_active_for_jam', sa.Boolean(), nullable=True))

    # Update existing users to have the default role
    op.execute("UPDATE users SET role = 'jammer' WHERE role IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active_for_jam')
        batch_op.drop_column('instruments_played')
        batch_op.drop_column('genres_enjoyed')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
