"""Add location_name to instruments

Revision ID: d3e7ffd5dbeb
Revises: 2ac78daab350
Create Date: 2025-12-20 16:41:58.312449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e7ffd5dbeb'
down_revision = '2ac78daab350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_name', sa.String(length=255), nullable=True))
    op.add_column('instruments', sa.Column('location_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'location_name')
    op.drop_column('users', 'location_name')
    # ### end Alembic commands ###
