"""add brand column to instruments

Revision ID: e1cc204f95b4
Revises: 5b2e118eb330
Create Date: 2026-01-05 16:44:43.131116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cc204f95b4'
down_revision = '5b2e118eb330'
branch_labels = None
depends_on = None


"""add brand column to instruments

Revision ID: e1cc204f95b4
Revises: 5b2e118eb330
Create Date: 2026-01-05 16:44:43.131116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cc204f95b4'
down_revision = '5b2e118eb330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The brand column was already added in the previous migration 5b2e118eb330
    # This migration is redundant but kept for migration history consistency
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The brand column should not be dropped as it was added in a previous migration
    pass
    # ### end Alembic commands ###
